spring:
  application:
    name: SB-Security-04-JWT-token-Login_Register
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/mageshit2025
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: cdp
      password: asdf

server:
  port: 1122
  